### ISSUE TITLE
Not able to start the sample simulation

### ISSUE THREAD

**Issue by Shlok-Jain** [neobotix/neo_mpc_planner2#33]
I set up and installed all the dependencies, and tried to run the simulation. The code ran, but there was no simulation running. Can someone please help?

I know I should not post it on issues, but I am new to GitHub and didn't find any other place to do so. Thanks!

**Comment by padhupradheep** [comment]
Hey, 

Please follow the documentation here to [start the simulation](https://neobotix-docs.de/ros/ros2/installation.html) and update this controllers in the configs accordingly. Feel free to continue the thread if you have any problems in setting it up.
